name: endorse
homepage: "https://github.com/kirklink/endorse"
description: "Library for validating arbitrary objects such as API responses."
version: 0.1.0-nullsafety.2
environment:
  sdk: '>=2.15.0 <4.0.0'
dependencies:
  recase: ^4.0.0
  source_gen: ^1.0.0
  analyzer: ^1.5.0
  build: ^2.0.1
dev_dependencies:
  build_runner: ^2.0.2
  pedantic: ^1.11.0
  